#!/usr/bin/env bash

# Set environment variables
export FLASK_APP=backend/
## Export database URI
export DATABASE_URI=mysql://admin:0817707250@pld-plus-db.cjgka2mua43c.eu-north-1.rds.amazonaws.com:3306/PLD_PLUS

# Export secret token
export SECRET_KEY=0db41072b6098302ab7853c8ee08998b

# Prompt the user
read -rp "Do you want to run Gunicorn? (y/n): " choice

# Check the user's choice
if [[ "$choice" == [Yy]* ]]; then
    # User wants to run Gunicorn
    echo "Running Gunicorn..."
    gunicorn -c config/gunicorn_config.py backend.run:app
else
    # User chose not to run Gunicorn
    echo "Gunicorn execution skipped."
fi
